### ISSUE TITLE
Logger object not initialized when reading milestone file?

### ISSUE THREAD

**Issue by GhostGambler** [chgagne/beagle#19]
Hi

There is another issue with the logging calls and a not-yet-initialized logger object, if one starts OpenBeagle with a milestone file as argument.

I think the logging calls in `Core/Evolver.cpp` in the method `void Evolver::readMilestone(const std::string& inFileName, System& ioSystem)` need to be replaced with `Beagle_AddToLogBufferM`, but this does not fix the problem completely: 
```
#10 0x0000000000636f88 in Beagle::Logger::Entry::~Entry (this=0x7fffffffbdc0, __in_chrg=<optimized out>, __vtt_parm=<optimized out>) at Beagle/Core/Logger.hpp:379
#11 0x0000000000830657 in Beagle::Evolver::registerOperatorParams (this=0xcbb150, ioSystem=...) at Beagle/Core/Evolver.cpp:823
#12 0x000000000082dea7 in Beagle::Evolver::readMilestone (this=0xcbb150, inFileName="milestone_g50.obm", ioSystem=...) at Beagle/Core/Evolver.cpp:624
#13 0x000000000082c9e9 in Beagle::Evolver::parseCommandLine (this=0xcbb150, ioSystem=..., inArgc=5, inArgv=0x7fffffffd160) at Beagle/Core/Evolver.cpp:512
#14 0x000000000082a9af in Beagle::Evolver::initialize (this=0xcbb150, ioSystem=..., inArgc=5, inArgv=0x7fffffffd160) at Beagle/Core/Evolver.cpp:285
#15 0x000000000066d3ae in main ()
```

The method `registerOperatorParams` runs fine, if one does not read a milestone file, so I guess the logger is not correctly initialized. I did not find the problem, maybe you can take a look yourself.

**Comment by chgagne** [comment]
Sorry for taking that long, I was pretty busy. That should be fixed now if you take code in the head of master branch.

**Comment by ulrichgabor** [comment]
No problem, also took me a while to try it out, but it still does not work:
```
terminate called after throwing an instance of 'Beagle::InternalException'
  what():  Logger is not initialized, therefore logging is impossible. Logging before the initialization phase should be done through the log buffer, for instance by using macro Beagle_AddToLogBufferM.

[snip]
#10 0x0000000000636fd8 in Beagle::Logger::Entry::~Entry (this=0x7fffffffb2a0, __in_chrg=<optimized out>, __vtt_parm=<optimized out>)
    at .../ea-mast/../beagle/src/Beagle/Core/Logger.hpp:379
#11 0x000000000085ddb5 in Beagle::BreederNode::registerParams (this=0xcbc7e0, ioSystem=...) at .../beagle/src/Beagle/Core/BreederNode.cpp:66
#12 0x000000000081c0d8 in Beagle::ReplacementStrategyOp::registerParams (this=0xcca910, ioSystem=...) at .../beagle/src/Beagle/Core/ReplacementStrategyOp.cpp:100
#13 0x000000000078e7dd in Beagle::EC::OversizeOp::registerParams (this=0xcca910, ioSystem=...) at .../beagle/src/Beagle/EC/OversizeOp.cpp:67
#14 0x00000000008310f5 in Beagle::Evolver::registerOperatorParams (this=0xcba310, ioSystem=...) at .../beagle/src/Beagle/Core/Evolver.cpp:875
#15 0x000000000082e46b in Beagle::Evolver::readMilestone (this=0xcba310, inFileName="data/model5/EARun1/milestone_g30.obm", ioSystem=...)
    at .../beagle/src/Beagle/Core/Evolver.cpp:642
#16 0x000000000082cfdf in Beagle::Evolver::parseCommandLine (this=0xcba310, ioSystem=..., inArgc=5, inArgv=0x7fffffffcdc0) at .../beagle/src/Beagle/Core/Evolver.cpp:528
#17 0x000000000082ac08 in Beagle::Evolver::initialize (this=0xcba310, ioSystem=..., inArgc=5, inArgv=0x7fffffffcdc0) at .../beagle/src/Beagle/Core/Evolver.cpp:301
#18 0x000000000066d5b6 in main ()
```

**Comment by chgagne** [comment]
Hi,

I am not able to reproduce your error. Can you provide me with a specific example from Open BEAGLE, along with a configuration file and a command-line, in order to allow me to reproduce the problem?

Be sure to use the latest version from github.

Best,

Christian
